// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNC9ut8M8VVckG8bAn6vaVzvfGSLNKg4Y',
    appId: '1:864588086270:web:b2e2f6c3793d44efa15eaf',
    messagingSenderId: '864588086270',
    projectId: 'crudbooking-43175',
    authDomain: 'crudbooking-43175.firebaseapp.com',
    storageBucket: 'crudbooking-43175.firebasestorage.app',
    measurementId: 'G-QG1915LBH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSwOuu50UZKNhHSRV4JSXz16m7uy3qRTI',
    appId: '1:864588086270:android:99b061f59f30c872a15eaf',
    messagingSenderId: '864588086270',
    projectId: 'crudbooking-43175',
    storageBucket: 'crudbooking-43175.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-G3fAlakj6nAgMvYUiGSzIuCPVjsd26A',
    appId: '1:864588086270:ios:8749ec79aca5f549a15eaf',
    messagingSenderId: '864588086270',
    projectId: 'crudbooking-43175',
    storageBucket: 'crudbooking-43175.firebasestorage.app',
    iosBundleId: 'com.example.crudPenyewaan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-G3fAlakj6nAgMvYUiGSzIuCPVjsd26A',
    appId: '1:864588086270:ios:8749ec79aca5f549a15eaf',
    messagingSenderId: '864588086270',
    projectId: 'crudbooking-43175',
    storageBucket: 'crudbooking-43175.firebasestorage.app',
    iosBundleId: 'com.example.crudPenyewaan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNC9ut8M8VVckG8bAn6vaVzvfGSLNKg4Y',
    appId: '1:864588086270:web:b57cbf86aaf71d0ea15eaf',
    messagingSenderId: '864588086270',
    projectId: 'crudbooking-43175',
    authDomain: 'crudbooking-43175.firebaseapp.com',
    storageBucket: 'crudbooking-43175.firebasestorage.app',
    measurementId: 'G-1CNHD34CYL',
  );
}
